package com.moviebuff.entities;

public enum Genre {
	ACTION, THRILLER, SCI_FI, ADVENTURE,
	CRIME, DRAMA, FANTASY, COMEDY, HISTORY, BIOGRAPHY,
	MYSTERY, ROMANCE, ANIMATION, WESTERN, FAMILY, HORROR, 
	DOCUMENTARY, NEWS, TALK_SHOW, WAR
	
}
